import type { StayQuote } from "./types";
import { asPrice } from "./format";

export interface ComparisonResult {
  hotel: StayQuote;
  airbnb: StayQuote;
  nights: number;
  nightlySaving: number;
  totalSaving: number;
  winner: StayQuote;
  rationale: string;
}

/**
 * Normalises a hotel and an Airbnb into the side-by-side recommendation from
 * spec §3.3. In production the rationale paragraph is generated by Claude
 * (weighing price, flexibility, and proximity to itinerary spots); here we
 * compute a deterministic version that weighs price against location.
 */
export function buildComparison(hotel: StayQuote, airbnb: StayQuote, nights: number): ComparisonResult {
  const nightlySaving = hotel.pricePerNight - airbnb.pricePerNight;
  const totalSaving = nightlySaving * nights;
  const locationGap = hotel.locationScore - airbnb.locationScore;

  let winner = hotel;
  let rationale: string;
  if (locationGap >= 1.5 && Math.abs(totalSaving) < 600) {
    winner = hotel;
    rationale = "Hotel recommended — location advantage outweighs the price saving for this trip.";
  } else if (nightlySaving > 0) {
    winner = airbnb;
    rationale = `Airbnb saves ${asPrice(nightlySaving)}/night = ${asPrice(totalSaving)} over ${nights} nights.`;
  } else {
    winner = hotel;
    rationale = "Hotel recommended — better value and flexibility for these dates.";
  }

  return { hotel, airbnb, nights, nightlySaving, totalSaving, winner, rationale };
}
