import Foundation
import SwiftData

/// A full trip plan generated by Claude from the trip profile. Stored in
/// SwiftData + synced via CloudKit; cached locally for offline (airplane mode).
@Model
final class Itinerary {
    var id: UUID = UUID()
    var destinationName: String = ""
    var arrival: Date = Date.now
    var departure: Date = Date.now
    var generatedAt: Date = Date.now

    @Relationship(deleteRule: .cascade, inverse: \ItineraryDay.itinerary)
    var days: [ItineraryDay] = []

    init(destinationName: String, arrival: Date, departure: Date) {
        self.destinationName = destinationName
        self.arrival = arrival
        self.departure = departure
    }

    /// Running total of estimated costs across all planned slots.
    var estimatedTotalPerPerson: Double {
        days.flatMap(\.slots).map(\.costPerPerson).reduce(0, +)
    }
}
