"use client";

import { useState } from "react";
import { CalendarPlus, FileDown, Share2 } from "lucide-react";
import { PageShell } from "@/components/ui/PageShell";
import { TripTabs } from "@/components/ui/TripTabs";
import { Button } from "@/components/ui/Button";
import { TripProfileForm } from "@/components/itinerary/TripProfileForm";
import { DayView } from "@/components/itinerary/DayView";
import { ItineraryMap } from "@/components/itinerary/ItineraryMap";
import { BudgetTracker } from "@/components/itinerary/BudgetTracker";
import { useStore } from "@/components/store";
import { generateItinerary, regenerateDay } from "@/lib/claude";
import { itineraryToICS } from "@/lib/ics";
import type { Itinerary, Period, Slot, TripProfile } from "@/lib/types";
import { cn } from "@/lib/cn";

const PERIODS: Period[] = ["morning", "afternoon", "evening"];

export default function ItineraryPage({ params }: { params: { id: string } }) {
  const { trips, itineraries, hydrated, setItinerary, createShare } = useStore();
  const trip = trips.find((t) => t.id === params.id);
  const itinerary = itineraries[params.id];

  const [generating, setGenerating] = useState(false);
  const [regenerating, setRegenerating] = useState(false);
  const [dayIdx, setDayIdx] = useState(0);
  const [shareLink, setShareLink] = useState<string | null>(null);

  if (!hydrated) return <PageShell mode="planning"><div className="h-80 animate-pulse rounded-2xl bg-[var(--surface-2)]" /></PageShell>;
  if (!trip) return <PageShell mode="planning"><p className="ps-muted py-20 text-center">Trip not found.</p></PageShell>;

  async function onGenerate(profile: TripProfile) {
    setGenerating(true);
    const it = await generateItinerary(profile, trip!.destinationName, trip!.departDate, trip!.returnDate, trip!.id);
    setItinerary(it);
    setGenerating(false);
  }

  function patchDay(dayId: string, updater: (d: Itinerary["days"][number]) => Itinerary["days"][number]) {
    if (!itinerary) return;
    setItinerary({ ...itinerary, days: itinerary.days.map((d) => (d.id === dayId ? updater(d) : d)) });
  }

  async function onRegenerate(dayId: string) {
    if (!itinerary) return;
    const day = itinerary.days.find((d) => d.id === dayId);
    if (!day) return;
    setRegenerating(true);
    const fresh = await regenerateDay(day, itinerary.destinationName);
    patchDay(dayId, (d) => ({ ...d, theme: fresh.theme, slots: fresh.slots }));
    setRegenerating(false);
  }

  function onReplaceSlot(dayId: string, index: number, slot: Slot) {
    patchDay(dayId, (d) => ({ ...d, slots: d.slots.map((s, i) => (i === index ? slot : s)) }));
  }

  function onReorder(dayId: string, from: number, to: number) {
    patchDay(dayId, (d) => {
      const slots = [...d.slots];
      const [moved] = slots.splice(from, 1);
      slots.splice(to, 0, moved);
      return { ...d, slots: slots.map((s, i) => ({ ...s, period: PERIODS[i] ?? s.period })) };
    });
  }

  function downloadICS() {
    if (!itinerary) return;
    const blob = new Blob([itineraryToICS(itinerary)], { type: "text/calendar" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `peak-signal-${trip!.destination}.ics`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function share() {
    const token = createShare(trip!.id);
    setShareLink(`${location.origin}/share/${token}`);
  }

  // ---- Profile form (no itinerary yet) ----
  if (!itinerary) {
    return (
      <PageShell mode="planning">
        <div className="animate-fade-up space-y-6">
          <div>
            <TripTabs id={trip.id} />
            <h1 className="mt-4 text-3xl font-semibold tracking-tighter2">Plan {trip.destinationName}</h1>
            <p className="ps-muted mt-1 text-[15px]">A fresh profile for this trip — who&rsquo;s coming changes everything.</p>
          </div>
          <TripProfileForm defaultTravellers={trip.travellers} generating={generating} onGenerate={onGenerate} />
        </div>
      </PageShell>
    );
  }

  // ---- Planner ----
  const days = [...itinerary.days].sort((a, b) => a.dayIndex - b.dayIndex);
  const current = days[Math.min(dayIdx, days.length - 1)];

  return (
    <PageShell mode="planning" wide>
      <div className="animate-fade-up space-y-6">
        <div className="flex flex-wrap items-end justify-between gap-4">
          <div>
            <TripTabs id={trip.id} />
            <h1 className="mt-4 text-3xl font-semibold tracking-tighter2">{itinerary.destinationName}</h1>
            <p className="ps-muted mt-1 text-[14px]">{days.length}-day plan · generated by Claude</p>
          </div>
          <div className="flex flex-wrap gap-2">
            <Button variant="secondary" size="sm" onClick={downloadICS}><CalendarPlus size={15} /> Calendar (.ics)</Button>
            <Button variant="secondary" size="sm" onClick={() => window.print()}><FileDown size={15} /> PDF</Button>
            <Button size="sm" onClick={share}><Share2 size={15} /> Share</Button>
          </div>
        </div>

        {shareLink && (
          <div className="ps-card flex items-center gap-3 p-3 text-[13px]">
            <span className="ps-muted">Read-only link:</span>
            <code className="ps-data truncate text-accent">{shareLink}</code>
            <button onClick={() => navigator.clipboard?.writeText(shareLink)} className="ml-auto rounded-full bg-accent px-3 py-1 text-white">Copy</button>
          </div>
        )}

        <div className="flex flex-wrap gap-2">
          {days.map((d, i) => (
            <button
              key={d.id}
              onClick={() => setDayIdx(i)}
              className={cn(
                "rounded-full px-4 py-1.5 text-[13px] font-medium transition",
                i === dayIdx ? "bg-accent text-white shadow-sm" : "border ps-hairline bg-[var(--surface-2)] ps-muted hover:text-[var(--text)]",
              )}
            >
              Day {d.dayIndex + 1}
            </button>
          ))}
        </div>

        <div className="grid gap-6 lg:grid-cols-[1fr_360px]">
          <DayView
            key={current.id}
            day={current}
            destination={itinerary.destinationName}
            regenerating={regenerating}
            onRegenerate={() => onRegenerate(current.id)}
            onReplaceSlot={(index, slot) => onReplaceSlot(current.id, index, slot)}
            onReorder={(from, to) => onReorder(current.id, from, to)}
          />
          <div className="space-y-6">
            <ItineraryMap itinerary={itinerary} />
            <BudgetTracker itinerary={itinerary} />
          </div>
        </div>
      </div>
    </PageShell>
  );
}
